name: Unit Tests

on:
  push:
  workflow_dispatch:

jobs:
  run-tests:
    name: Check Unit Tests
    runs-on: ${{ vars.RUNNER_LABEL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 26
      - run: npm ci
      - run: npm run test
